app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include('userApp.urls')),
    path("", include('patient.urls'))
]

patient/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.patient_index, name='patient_index'),
    path("model", views.patient_model, name='patient_model'),
    path("model2", views.patient_model2, name='patient_model2'),
    path("patient/index", views.patient_list, name='patient_list'),
    path("patient/add", views.patient_create, name='patient_add'),
    path("patient/show/<int:id>", views.patient_show, name='patient_show'),
    path("patient/edit/<int:id>", views.patient_edit, name='patient_edit'),
    path("patient/update/<int:id>", views.patient_update, name='patient_update'),
    path("patient/delete/<int:id>", views.patient_delete, name='patient_delete'),
    path("patient/migrate", views.patient_migrate, name='patient_migrate'),
    path("select2/", include("django_select2.urls")),
    path("tagComplate", views.tagComplate, name='tag-complate'),
]

patient/models.py
from django.db import models, connection


# Create your models here.
class Gender(models.TextChoices):
    MALE = 'erkak', "Erkak"
    FEMALE = 'ayol', "Ayol",


class Patient(models.Model):
    age = models.IntegerField(verbose_name="Yoshi")
    gender = models.CharField(verbose_name="Jinsi", max_length=10, choices=Gender.choices)
    symptom = models.CharField(verbose_name="Simtomlar", max_length=250)
    event = models.CharField(verbose_name="Xulosa", max_length=250)

    def __str__(self):
        return self.event

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {0}'.format(cls._meta.db_table))

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['age', 'gender', 'symptom', 'event'],
                                    name='uk_patient_age_gender_symtom_event')
        ]
        db_table = "patient"

patient/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget, Select2TagWidget

from .models import Patient
from django_select2 import forms as s2forms


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = "__all__"


class SymptomWidget(s2forms.Select2MultipleWidget):
    search_fields = [
        "symptom__icontains",
        # "email__icontains",
    ]


# class Gender(models.TextChoices):
#     MALE = 'erkak', "Erkak"
#     FEMALE = 'ayol', "Ayol",
GEEKS_CHOICES = (
    ("erkak", "Erkak"),
    ("ayol", "Ayol"),
)


class PatientSymptom(forms.Form):
    age = forms.IntegerField(label='Yoshi')
    gender = forms.ChoiceField(choices=GEEKS_CHOICES, label='Jinsi')
    model = Patient.objects.values('symptom').distinct().all()
    choice = list()
    for item in model:
        choice.append((item['symptom'], item['symptom']))
    # print(choice)
    symptom = forms.MultipleChoiceField(widget=Select2MultipleWidget, choices=choice, label='Kasallik belgilari')
    # class Meta:
    #     model = Patient
    #     fields = ['age', 'gender', 'symptom']
    #     widgets = {
    #         'symptom': SymptomWidget,
    #     }

patient/views.py
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
# Create your views here.
from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView
import csv
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static

from app import settings
from patient.forms import PatientForm, PatientSymptom
from patient.models import Patient
from django.views import generic
from django.core import serializers
from django.http import HttpResponse
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pickle


@login_required()
def patient_create(req: HttpRequest):
    if req.method == 'POST':
        form = PatientForm(req.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('patient_list')
            except:
                pass
    else:
        form = PatientForm()

    return render(req, 'patient/create.html', {
        'form': form
    })


@login_required()
def patient_list(req: HttpRequest):
    items = Patient.objects.order_by("symptom").all()
    return render(req, 'patient/list.html', {
        'items': items
    })


@login_required()
def patient_index(req: HttpRequest):
    # items = Patient.objects.all()
    # print(items)
    form = PatientSymptom()
    result = list()
    prediction_probabilities = []
    symptom = list()
    age = 1
    gender = 'Erkak'
    if req.method == 'POST':
        data = req.POST
        filename = 'patient_model.sav'
        loaded_model = pickle.load(open(filename, 'rb'))
        # for item in data.get('symptom'):
        model = Patient.objects.values('symptom').distinct().all()
        test1 = list()
        symp = data.getlist('symptom')
        age = int(data.get('age'))
        gender = data.get('gender')

        for item in model:
            ok = False
            for value in symp:
                if value == item['symptom']:
                    ok = True
            test1.append(ok)
        test1.append(age)
        if req.POST['gender'] == 'erkak':
            test1.append(0)
        else:
            test1.append(1)

        result = loaded_model.predict([test1])
        # loaded_model
        probabilities = loaded_model.predict_proba([test1])
        dataset = pd.read_csv('write_to_csv.csv', delimiter=';')
        # datasetni shuffle qilish
        dataset = dataset.sample(frac=1)
        types = dataset['xulosa'].unique()


        for i in range(len(loaded_model.classes_)):
            prediction_probabilities.append(
                {"text": loaded_model.classes_[i], 'result': int(probabilities[0][i] * 1000) / 10.})

        prediction_probabilities.sort(key=sort_by, reverse=True)
        symptom = symp
    return render(req, 'patient/index.html', {
        'form': form,
        'result': result,
        'symptom': symptom,
        'prediction': prediction_probabilities[:min(len(prediction_probabilities), 3)],
        'age': age,
        'gender': gender,
    })


@login_required()
def patient_model(req: HttpRequest):
    if req.method == 'POST':
        items = Patient.objects.values('symptom').distinct().all()
        item_to = []
        for item in items:
            item_to.append(item['symptom'])
        item_to.append("yoshi")
        item_to.append("jinsi")
        item_to.append("xulosa")
        item2 = Patient.objects.values('age', 'gender', 'event').distinct().all()
        values = []
        for item in item2:
            itemSymptoms = Patient.objects.filter(age=item['age'], gender=item['gender'],
                                                  event=item['event']).values(
                'symptom').distinct().all()
            item_val = []
            for value in items:
                print(value)
                if itemSymptoms.filter(symptom=value['symptom']):
                    item_val.append(True)
                else:
                    item_val.append(False)
            item_val.append(item['age'])
            if item['gender'] == 'erkak':
                item_val.append(0)
            else:
                item_val.append(1)
            item_val.append(item['event'])
            values.append(item_val)

        with open('write_to_csv.csv', 'w', ) as file:
            writer = csv.writer(file, delimiter=';')
            writer.writerow(item_to)
            writer.writerows(values)
        dataset = pd.read_csv('write_to_csv.csv', delimiter=';')

        # datasetni shuffle qilish
        dataset = dataset.sample(frac=1)

        # columnla soni 52 bo'lani uchun xulosani addelniy olib qolgan 51 donasi X ga yuklangan
        X = dataset[list(dataset.columns[:-1])]
        y = dataset['xulosa']

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        logisticRegr = LogisticRegression()
        logisticRegr.fit(X_train, y_train)
        # predictions = logisticRegr.predict(X_test)
        score = logisticRegr.score(X_test, y_test)
        # print(score)

        filename = 'patient_model.sav'
        pickle.dump(logisticRegr, open(filename, 'wb'))

    return redirect("patient_index")


@login_required()
def patient_model2(req: HttpRequest):
    if req.method == 'POST':
        items = Patient.objects.values('symptom').distinct().all()
        item_to = []
        for item in items:
            item_to.append(item['symptom'])
        item_to.append("yoshi")
        item_to.append("jinsi")
        item_to.append("xulosa")
        item2 = Patient.objects.values('age', 'gender', 'event').distinct().all()
        values = []
        for item in item2:
            itemSymptoms = Patient.objects.filter(age=item['age'], gender=item['gender'],
                                                  event=item['event']).values(
                'symptom').distinct().all()
            item_val = []
            for value in items:
                print(value)
                if itemSymptoms.filter(symptom=value['symptom']):
                    item_val.append(value['symptom'])
                else:
                    item_val.append(None)
            item_val.append(item['age'])
            item_val.append(item['gender'])
            item_val.append(item['event'])
            values.append(item_val)

        with open('write_to2_csv.csv', 'w', ) as file:
            writer = csv.writer(file, delimiter=';')
            writer.writerow(item_to)
            writer.writerows(values)

    return redirect("patient_index")


@login_required()
def patient_show(req: HttpRequest, id: int):
    item = Patient.objects.get(id=id)

    return render(req, 'patient/show.html', {
        'item': item
    })


@login_required()
def patient_edit(req: HttpRequest, id: int):
    item = get_object_or_404(Patient, id=id)
    form = PatientForm(req.POST or None, instance=item)
    if form.is_valid():
        try:
            form.save()
        except:
            pass
        return redirect('patient_list')
    return render(req, 'patient/edit.html', {
        'form': form
    })


@login_required()
def patient_update(req: HttpRequest, id: int):
    item = Patient.objects.get(id=id)
    form = PatientForm(req.POST, instance=item)
    if form.is_valid():
        form.save()
        return redirect("patient_list")

    return render(req, 'patient/edit.html', {
        'item': item
    })


@login_required()
def patient_delete(req: HttpRequest, id: int):
    item = Patient.objects.get(id=id)
    item.delete()
    return redirect("patient_list")


@login_required()
def patient_migrate(req: HttpRequest):
    Patient.objects.all().delete()
    Patient.truncate()
    a_path = settings.BASE_DIR
    a_path = str(a_path) + '/file1.csv'

    file = open(a_path)
    csv_reader = csv.reader(file, delimiter=';')
    for value in csv_reader:
        a = int(value[1])
        b = int(value[2])
        s = value[0].split(',')
        if int(value[3]) == int(value[4]):
            for i in range(a, b + 1):
                for l in s:
                    add_patient(l, i, 'erkak', value[5])
                    add_patient(l, i, 'ayol', value[5])
        elif int(value[3]) > int(value[4]):
            for i in range(a, b + 1):
                for l in s:
                    add_patient(l, i, 'erkak', value[5])
            for i in range(a, b + 1, 2):
                for l in s:
                    add_patient(l, i, 'ayol', value[5])
        else:
            for i in range(a, b + 1, 2):
                for l in s:
                    add_patient(l, i, 'erkak', value[5])
            for i in range(a, b + 1):
                for l in s:
                    add_patient(l, i, 'ayol', value[5])

    # print(int(item[2]) - int(item[1]) + 1)
    file.close()
    return redirect("patient_list")


# class BookCreateView(generic.CreateView):
#     model = Patient
#     form_class = PatientSymptom
#     success_url = "/"

def add_patient(sym: str, age: int, gender: str, event: str):
    p = Patient()
    p.age = age
    p.symptom = sym.lower()
    p.gender = gender
    p.event = event.lower()
    return p.save()


def tagComplate(req: HttpRequest):
    # print(req.GET['q'])
    model = Patient.objects.values('symptom').all()
    choice = list()
    for item in model:
        choice.append({"id": item['symptom'], "text": item['symptom']})
    return JsonResponse(choice, safe=False)


def sort_by(e):
    return float(e['result'])

# class PatientDetailView(DetailView):
#     model = Patient
#
#
# class PatientCreateView(CreateView):
#     model = Patient
#     form_class = PatientForm
#     success_url = reverse_lazy('patient:patient_list')
#
#
# class PatientUpdateView(UpdateView):
#     model = Patient
#     form_class = PatientForm
#     success_url = reverse_lazy('patient:patient_list')

templates/patient/create.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group row">
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/patient/edit.html
{% extends 'main.html' %}
{% block content %}
    <h2>Tahrilash</h2>

    {% load crispy_forms_tags %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group row">
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/patient/index.html
{% extends 'main.html' %}
{% block content %}
    <br>
    <hr>
    <div class="row">
        <div class="col-md-3">
            <form action="{% url 'patient_model' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary ">Model</button>
            </form>
        </div>
        {#        <div class="col-md-3">#}
        {#            <form action="{% url 'patient_model2' %}" method="post">#}
        {#                {% csrf_token %}#}
        {#                <button type="submit" class="btn btn-primary ">Model2</button>#}
        {#            </form>#}
        {#        </div>#}
    </div>



    <br/>
    <hr>
    <h1>Simptomlarni teshkirish</h1>
    <form method="POST">
        {% csrf_token %}
        {#        {{ form.as_p }}#}
        {#        <input type="submit">#}
        {#    </form>#}
        {% load crispy_forms_tags %}
        {{ form|crispy }}
        <button class="btn btn-primary">Teshkirish</button>
    </form>
    {% if prediction %}
        <hr>
        <ul>
            {% for item in symptom %}
                <li>{{ item }}</li>
            {% endfor %}
            <li>Yoshi: {{ age }}</li>
            <li>Jinsi: {{ gender }}</li>
        </ul>
        {% for item in prediction %}
            <h4> {{ forloop.counter }} . <b class="text-capitalize">{{ item.text }}</b>, ehtimolligi: {{ item.result }}
                %</h4>
        {% endfor %}

    {% endif %}
{% endblock %}
{% load static %}
{% block js %}
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_symptom').select2();

            {#$('#id_symptom').select2({#}
            {#    ajax: {#}
            {#        url: "{% url 'tag-complate' %}",#}
            {#        dataType: "json",#}
            {#        processResults: function (data) {#}
            {#            // Transforms the top-level key of the response object from 'items' to 'results'\#}
            {#            console.log(data);#}
            {#            return {#}
            {#                results: data#}
            {#            };#}
            {#        }#}
            {#    },#}
            {#    minimumInputLength: 2,#}
            {#    placeholder: "Tag",#}
            {#    theme: "bootstrap-5",#}
            {# }); #}

            //.id_tag
        }); //.document
    </script>
{% endblock %}
{% block head %}
    <link href="{% static '/css/select2.min.css' %}" rel="stylesheet"/>
{% endblock %}

templates/patient/list.html
{% extends 'main.html' %}
{% block content %}
    <h1>Simptomlar</h1>
    <a href="{% url 'patient_add' %}" class="btn btn-primary">Qo'shish </a>
    <a href="{% url 'patient_migrate' %}" class="btn btn-info">Migrate </a>
    <br/>
    <hr>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Yoshi</th>
            <th>Jinsi</th>
            <th>Simtom</th>
            <th>Xulosa</th>
            <th>Rahirilash</th>
        </tr>
        </thead>
        {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.age }}</td>
                <td>{{ item.gender }}</td>
                <td>{{ item.symptom }}</td>
                <td>{{ item.event }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{% url 'patient_edit' id=item.id %}" class="btn btn-warning btn-sm">o'zgartish</a>
                        <a href="{% url 'patient_delete' id=item.id %}" class="btn btn-danger btn-sm">o'chirish</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}